title: <p align="center"> Faiz Sobhani </p>
logo: /assets/img/faiz_picture.jpg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/faiz-sobhani/">LinkedIn</a> |
  <a href="https://github.com/faizsobhani">GitHub</a>

  </p>



theme: jekyll-theme-minimal
